### ISSUE TITLE
C lint enhancements

### ISSUE THREAD

**Issue by mcandre** [rillig/pkglint#3]
Hey, this is of course for the lint project, not specifically pkglint. Didn't know where else to ask.

I would love to be able to lint more modern C projects with lint.

* C17 support
* C2x AKA C23 support
* FreeBSD entries in pkgsrc, pkgin, pkg
* OpenBSD, Hardened BSD, DragonflyBSD, MirOS ports
* macOS entry in Homebrew
* Windows entry in Chocolatey
* Haiku, Illumos, Plan 9 ports

(I like for my C projects to build incredibly portably.)

As a workaround, I am applying some C++ linters, which usually support C code as well. This includes compiler warnings, cppcheck, and cpplint.

**Comment by rillig** [comment]
Hi Andrew,

For off-topic topics, you already know my e-mail address. As this "feature request" is not related to pkglint, I'll close this issue.

Regarding C lint:
* I don't have plans to port NetBSD lint to other platforms, it should be relatively easy though.
* [Lint](https://github.com/NetBSD/src/tree/trunk/usr.bin/xlint) consists of the main driver named `xlint`.
    * The `x` in `xlint` is only needed to avoid a naming conflict since `make lint` needs to _run_ the installed lint, as everywhere else, and not _build_ the program named `lint`.
    * For each translation unit, `xlint` first runs the C preprocessor.
    * Then, it runs `lint1` to check a single translation unit in isolation.
    * After checking the translation units, it runs `lint2` to cross-check the translation units.
    * The helper programs `lint1` and `lint2` end up in `libexec/`, as they are not intended to be run directly.
* There are [lots of unit tests](https://github.com/NetBSD/src/tree/trunk/tests/usr.bin/xlint).
    * The [tests for `lint1`](https://github.com/NetBSD/src/tree/trunk/usr.bin/xlint/lint1#tests) are driven by `t_integration.sh`, which runs `lint1` on each translation unit.

Regarding compiler warnings, I liked the compilers from IRIX 6.5 and SunPro, as they were stricter than GCC when I tried them almost 20 years ago. No idea how they developed further.

In your linter list, you don't yet mention [Clang-Tidy](https://clang.llvm.org/extra/clang-tidy/), which provides more guidance than the Clang compiler.

Roland
